### ISSUE TITLE
Sort by parent device / usb port ?

### ISSUE THREAD

**Issue by sduponch** [briankendall/devreorder#7] opened 2017-09-29 13:22 UTC
Hi,

I have an Arcade cabinet with two Zero Delay USB Encoder on a PC.
As the two devices have the same name, is there a way to sort them by the USB port where they are connected ?

Best regards,
DUPONCHEEL Sébastien

**Comment by briankendall** [comment] 2017-10-02 17:51
@sduponch Any particular reason you closed this issue?

**Comment by sduponch** [comment] 2017-10-03 14:56
@briankendall no, i just plan to change my HID interfaces for an arduino/teensy++ based one.
But if you think this is possible :)

**Comment by briankendall** [comment] 2017-10-03 14:57
It may be possible. Next time I have a chance I'll look into it.

**Comment by billwarnockjr** [comment] 2018-02-28 15:42
I am having a very similar issue.  I bought these two arcade usb encoders from amazon.  They are the same HID, same name, use the same built in driver, etc,. I primarily use theses controllers for various emulators, but every time I reboot, Windows changes the order of the Joystick ID.  I've been looking around forever and stumbled upon devreorder, and my specific issue here. Do you think devreorder can help me?

**Comment by briankendall** [comment] 2018-04-13 17:55
Closing as this is a duplicate of #8

**Closed by briankendall** 2018-04-13 17:55 UTC

**Comment by briankendall** [comment] 2018-04-16 18:46
FYI: if anyone is still watching this issue, check out [release 1.0.2](https://github.com/briankendall/devreorder/releases/tag/v1.0.2)

**Comment by sduponch** [comment] 2018-04-17 07:41
Testing it ASAP, thank you :)
