### ISSUE TITLE
2 joypads, same name for both

### ISSUE THREAD

**Issue by DJTraffik** [briankendall/devreorder#11] opened 2018-04-08 23:08 UTC
Hi, my IPAC arcade board gives me 2 joypads but they both have the same top level name.
They have different ID numbers.
Can devreorder use ID numbers instead of top level names?

**Comment by briankendall** [comment] 2018-04-13 17:54
I think this issue is probably a duplicate of #8 

Let me know if it isn't and I'll keep it open, otherwise I'll close the issue in a few days.

**Comment by DJTraffik** [comment] 2018-04-14 01:01
Yes it is but I'm unsure of the issue has been addressed. I'm not seeing a
solution to sorting controllers with the same top level name.
Sorry for the duplicate, you can close the issue.

Nat.

**Comment by briankendall** [comment] 2018-04-14 04:05
@DJTraffik You're correct, there isn't a fix yet. I intend to try and implement it soon but I'm constantly busy with other projects so I can't make any promises as to when it'll be done!

**Closed by briankendall** 2018-04-14 04:05 UTC

**Comment by DJTraffik** [comment] 2018-04-14 08:42
I understand mate, what you've done so far is awesome, a fix would be
double awesome :)

**Comment by briankendall** [comment] 2018-04-16 18:47
@DJTraffik Check out [release 1.0.2](https://github.com/briankendall/devreorder/releases/tag/v1.0.2) and the new instructions in the README file.
